verbose: true
image_format: png
dpi_val: 300
summary_plots: true
print_summary: false
plot_animations: true
plot_bias: false
plot_target: true
global_plotting_options:
  image_format: png
  animation_format: mp4
  dpi_val: 300
  ERA5:
    use_datashader: false
    marker_size: 4
    scale_marker_size: true
evaluation:
  metrics: ["rmse"]
  regions:
  - global
  summary_plots: true
  summary_dir: ./plots/
  print_summary: false
  log_scale: false
  add_grid: true
  plot_maps: true
  plot_animations: true
  plot_bias: false
  plot_target: true
  plot_ensemble: "members"
run_ids:
  iwr4tvaj:
    label: "iwr4tvaj"
    epoch: 0
    rank: 0
    streams:
      ERA5:
        channels: ['q_850', '2t']
        evaluation:
          sample: "all"
          forecast_step: "all"
        plotting:
          sample: "all"
          forecast_step: "all"
          plot_maps: true
          plot_animations: true
          plot_bias: false
          plot_target: true
          plot_histograms: false
          plot_ensemble: "members"
