verbose: true
image_format: png
dpi_val: 300
summary_plots: true
print_summary: false
plot_animations: true
plot_bias: false
plot_target: true
global_plotting_options:
  image_format: png
  animation_format: mp4
  dpi_val: 300
  ERA5:
    use_datashader: false
    marker_size: 4
    scale_marker_size: true
evaluation:
  metrics: ["psd", "rmse"]
  regions:
  - global
  summary_plots: true
  summary_dir: ./plots/20-08-26-diff-decft-new-runs/
  print_summary: false
  log_scale: false
  add_grid: true
  plot_maps: true
  plot_animations: true
  plot_bias: false
  plot_target: true
  plot_ensemble: "members"
  psd_step_montage_n: 25
run_ids:
  ku6i70v3:
    label: "forecast finetuned deterministic (skkbxfya -> dy0jlrmw)"
    epoch: 0
    rank: 0
    streams:
      ERA5:
        channels: ['q_850']
        evaluation:
          sample: "all"
          forecast_step: "all"
        plotting:
          sample: "all"
          forecast_step: "all"
          plot_maps: true
          plot_animations: true
          plot_bias: true
          plot_target: false
          plot_histograms: false
          plot_ensemble: "members"
  dabg7c2e:
    label: "cw6a4szu -> bwmk4ktc -> mibn2qst (from last chkpt)"
    epoch: 0
    rank: 0
    streams:
      ERA5:
        channels: ['q_850']
        evaluation:
          sample: "all"
          forecast_step: "all"
        plotting:
          sample: "all"
          forecast_step: "all"
          plot_maps: false
          plot_animations: false
          plot_bias: false
          plot_target: false
          plot_histograms: false
          plot_ensemble: "members"
  # r0cfonyp:
  #   label: "oliqngmf -> ss900572 -> mdxx9zg0"
  #   epoch: 0
  #   rank: 0
  #   streams:
  #     ERA5:
  #       channels: ['q_850']
  #       evaluation:
  #         sample: "all"
  #         forecast_step: "all"
  #       plotting:
  #         sample: "all"
  #         forecast_step: "all"
  #         plot_maps: true
  #         plot_animations: true
  #         plot_bias: true
  #         plot_target: false
  #         plot_histograms: false
  #         plot_ensemble: "members"
  # vuny076f:
  #   label: "new73gkw -> prkmwzlg -> la4ydebc"
  #   epoch: 0
  #   rank: 0
  #   streams:
  #     ERA5:
  #       channels: ['q_850']
  #       evaluation:
  #         sample: "all"
  #         forecast_step: "all"
  #       plotting:
  #         sample: "all"
  #         forecast_step: "all"
  #         plot_maps: true
  #         plot_animations: true
  #         plot_bias: true
  #         plot_target: false
  #         plot_histograms: false
  #         plot_ensemble: "members"
      
  # l05d7kvm:
  #   label: "skkbxfya -> ni41n7gy -> qtbn8vgb"
  #   epoch: 0
  #   rank: 0
  #   streams:
  #     ERA5:
  #       channels: ['q_850']
  #       evaluation:
  #         sample: "all"
  #         forecast_step: "all"
  #       plotting:
  #         sample: "all"
  #         forecast_step: "all"
  #         plot_maps: true
  #         plot_animations: true
  #         plot_bias: true
  #         plot_target: false
  #         plot_histograms: false
  #         plot_ensemble: "members"
  d45kmqzc:
    label: "skkbxfya -> mx7k88dy -> kz2n1t60"
    epoch: 0
    rank: 0
    streams:
      ERA5:
        channels: ['q_850']
        evaluation:
          sample: "all"
          forecast_step: "all"
        plotting:
          sample: "all"
          forecast_step: "all"
          plot_maps: true
          plot_animations: true
          plot_bias: true
          plot_target: false
          plot_histograms: false
          plot_ensemble: "members"
  # we3jpg28:
  #   label: "skkbxfya -> xxoplye6 -> hzsc0c1m"
  #   epoch: 0
  #   rank: 0
  #   streams:
  #     ERA5:
  #       channels: ['q_850']
  #       evaluation:
  #         sample: "all"
  #         forecast_step: "all"
  #       plotting:
  #         sample: "all"
  #         forecast_step: "all"
  #         plot_maps: true
  #         plot_animations: true
  #         plot_bias: true
  #         plot_target: false
  #         plot_histograms: false
  #         plot_ensemble: "members"
