


train :
  plot :
    huwssly8:
      slurm_id : 0
      description: "new MTM run diff"
    fqxmlc0v:
      slurm_id : 0
      description: "old MTM run diff"
    oliqngmf :
      slurm_id : 0
      description: "new MTM run"
    hsq7hsb6:
      slurm_id : 0
      description: "old MTM run"
    # perrjey5 :
    #   slurm_id : 0
    #   description: "N320-obs, with absolute coords, larger decoder, time_window_step=6h"
    # c71eo6pu :
    #   slurm_id : 0
    #   description: "perrjey5 contd : N320-obs, with absolute coords, larger decoder, time_window_step=6h"
    # xc1n4mw3 :
    #   slurm_id : 0
    #   description: "develop-ssl-diffusion-v1, config_forecasting_n320_obs.yml"
    # kdl0orun :
    #   slurm_id : 0
    #   description: "develop-ssl-diffusion-v1, config_forecasting_n320_obs.yml, streams_prepint, linear"
    # e4327u4h :
    #   slurm_id : 0
    #   description: "develop-ssl-diffusion-v1, config_forecasting_n320_obs.yml, streams_prepint, transformer"
    # d5nrjup6 :
    #   slurm_id : 0
    #   description: "develop"
    # iqbifydo :
    #   slurm_id : 0
    #   description: "develop-ssl-diffusion-v1"
    # fsvwafcl :
    #   slurm_id : 0
    #   description: "develop-ssl-diffusion-v1, FSDP"
    

# # develop-ssl-diffusion-v1, config_forecasting_n320_obs.yml
# 2026-07-25 15:41:27,781 - __main__ - INFO - ==============================================================================================
# 2026-07-25 15:41:27,781 - __main__ - INFO -   [train     ] 'train' | run_id=xc1n4mw3 | job_ids=[1043352, 1043353, 1043354, 1043355, 1043356, 1043357, 1043358, 1043359, 1043360, 1043361, 1043362, 1043363] | start_after=immediately | dir=/e/scratch/weatherai/slurm/slurm_weathergen_xc1n4mw3_dir
# 2026-07-25 15:41:27,781 - __main__ - INFO - ===============================================================================================

# # develop-ssl-diffusion-v1, config_forecasting_n320_obs.yml, streams_prepint, linear
# 2026-07-26 20:26:00,332 - __main__ - INFO - ==============================================================================================
# 2026-07-26 20:26:00,332 - __main__ - INFO -   [train     ] 'train' | run_id=kdl0orun | job_ids=[1048208, 1048209, 1048210, 1048211, 1048212, 1048213, 1048214, 1048215, 1048216, 1048217, 1048218, 1048219] | start_after=immediately | dir=/e/scratch/weatherai/slurm/slurm_weathergen_kdl0orun_dir
# 2026-07-26 20:26:00,332 - __main__ - INFO - ===============================================================================================

# # # develop-ssl-diffusion-v1, config_forecasting_n320_obs.yml, streams_prepint, transformer
# 2026-07-26 20:24:28,379 - __main__ - INFO - ==============================================================================================
# 2026-07-26 20:24:28,379 - __main__ - INFO -   [train     ] 'train' | run_id=e4327u4h | job_ids=[1048190, 1048191, 1048192, 1048193, 1048194, 1048195, 1048196, 1048197, 1048198, 1048199, 1048200, 1048201] | start_after=immediately | dir=/e/scratch/weatherai/slurm/slurm_weathergen_e4327u4h_dir
# 2026-07-26 20:24:28,379 - __main__ - INFO - ===============================================================================================
